using System.Globalization;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class BrainWaveScannerUiFragment : BoxContainer
{
    public BrainWaveScannerUiFragment()
    {
        RobustXamlLoader.Load(this);
    }

    public void UpdateState(BrainWaveUiState state)
    {
        ThetaValue.Text = FormatMetric(state.ThetaDrift);
        GammaValue.Text = FormatMetric(state.GammaSpikes);
        CoherenceValue.Text = FormatMetric(state.CoherenceDrop);
        NoiseValue.Text = FormatMetric(state.NoiseIndex);
        ConductivityValue.Text = FormatMetric(state.StressConductivity);

        NoScansLabel.Visible = state.Scans.Count == 0;
        ScansContainer.RemoveAllChildren();

        for (var i = state.Scans.Count - 1; i >= 0; i--)
        {
            var scan = state.Scans[i];
            var label = new Label
            {
                Text = Loc.GetString(
                    "brain-wave-scanner-entry",
                    ("subject", scan.SubjectName),
                    ("theta", scan.ThetaDrift.ToString("F0", CultureInfo.InvariantCulture)),
                    ("gamma", scan.GammaSpikes.ToString("F0", CultureInfo.InvariantCulture)),
                    ("coherence", scan.CoherenceDrop.ToString("F0", CultureInfo.InvariantCulture)),
                    ("noise", scan.NoiseIndex.ToString("F0", CultureInfo.InvariantCulture)))
            };

            ScansContainer.AddChild(label);
        }
    }

    private static string FormatMetric(float value)
    {
        return value.ToString("F1", CultureInfo.InvariantCulture);
    }
}
