using System;
using System.Collections.Generic;
using Content.Shared.CartridgeLoader.Cartridges;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.CartridgeLoader.Cartridges;

[GenerateTypedNameReferences]
public sealed partial class PsychInterpretUiFragment : BoxContainer
{
    public Action<List<string>>? RunInterpretation;
    private readonly Dictionary<string, CheckBox> _symptomChecks = new();

    public PsychInterpretUiFragment()
    {
        RobustXamlLoader.Load(this);
        InterpretButton.OnPressed += _ => RunInterpretation?.Invoke(GetSelectedSymptoms());
    }

    public void UpdateState(PsychInterpretUiState state)
    {
        LastScanLabel.Text = state.LastScan == null
            ? Loc.GetString("psych-interpret-last-scan-none")
            : Loc.GetString("psych-interpret-last-scan", ("target", state.LastScan.SubjectName));

        EnsureSymptoms(state.SymptomOptions, state.SelectedSymptoms);

        PatternValue.Text = state.PatternCode;
        ConfidenceValue.Text = $"{state.Confidence:P0}";
        ProtocolValue.Text = state.ProtocolHint;
        NotesLabel.Text = state.Notes;
    }

    private void EnsureSymptoms(List<string> options, List<string> selected)
    {
        SymptomsContainer.RemoveAllChildren();
        _symptomChecks.Clear();

        foreach (var symptom in options)
        {
            var check = new CheckBox
            {
                Text = Loc.GetString($"psych-interpret-symptom-{symptom}"),
                Pressed = selected.Contains(symptom)
            };

            _symptomChecks.Add(symptom, check);
            SymptomsContainer.AddChild(check);
        }
    }

    private List<string> GetSelectedSymptoms()
    {
        var selected = new List<string>();
        foreach (var (symptom, checkbox) in _symptomChecks)
        {
            if (checkbox.Pressed)
                selected.Add(symptom);
        }

        return selected;
    }
}
